### PR TITLE
adding CI for ngtcp2

### PR DESCRIPTION
**Pull request by baentsch**
Completing #159 as per https://github.com/open-quantum-safe/oqs-demos/pull/159#issuecomment-1288131807

### CODE REVIEW

**Comment by baentsch** [comment]
@Keelan10 please take a look whether this looks like a reasonable CI test. Thanks in advance.

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
@baentsch Do we need to update the list of demos in the main oqs-demos repository or on www.openquantumsafe.org?

**Comment by baentsch** [comment]
> @baentsch Do we need to update the list of demos in the main oqs-demos repository or on [www.openquantumsafe.org](http://www.openquantumsafe.org)?

The ngtcp2 link is already included in the main repo. For www.openquantumsafe.org please check https://github.com/dstebila/oqs-www-new/pull/111

**Comment by Keelan10** [comment]
> @Keelan10 please take a look whether this looks like a reasonable CI test. Thanks in advance.

LGTM

**Pull request merged**
