### PR TITLE
Changes that help make mosquito compatible with wolfMQTT.

### PR DESCRIPTION
**Pull request by anhu**

### CODE REVIEW

**Comment by anhu** [comment]
@chiachin2686 , Please have a look and let me know what you think.

**Comment by chiachin2686** [comment]
> @chiachin2686 , Please have a look and let me know what you think.

 I think this work is great. Are these changes going to be merged into wolfMQTT?

**Comment by anhu** [comment]
> Are these changes going to be merged into wolfMQTT?

Yes! Please see https://github.com/wolfSSL/wolfMQTT/pull/300 for the corresponding required changes in `wolfMQTT`. Those changes are going to be merged into `wolfMQTT` 's `master` branch.

**Comment by dstebila** [comment]
If these changes aren't going to be merged here, shall we eventually close the PR?

**Comment by anhu** [comment]
Would it be possible to have this live on as a draft PR or as a .patch file that is committed into the repo?

**Comment by baentsch** [comment]
> I am open to closing this PR. 

I'd also prefer that to have a clean view of the project status and close this here.

> Another possibility is to have this live on as a .patch file that is committed into the repo. I'm fine with both possibilities.

I'm personally somewhat hesitant towards having a product-specific patch in a "general purpose"/product-independent open-source repo. This hesitation is further exacerbated as this code reduces the QSC capabilities of `oqs-mosquito` _and_ has no interop test suite with WolfMQTT. 

So two options in my mind: 1) Could you check whether this could be hosted in the WolfSSL repos? 2) Would you want to amend this PR to make it into a patch-based script also including an interop test with WolfMQTT? _That_ I'd feel OK with hosting here (say in a subfolder called 'wolfmqtt-interop')

**Comment by anhu** [comment]
@baentsch , you've presented some great ideas here!! I think the easiest and simplest plan would be to host the patch on a wolfSSL repo. That said, it will take some some prioritization of resources. In the meantime, lets close this PR as a matter of housekeeping.

**Pull request closed without merging**
