### PR TITLE
Add wireshark with wolfSSL's names for OIDs and codepoints.

### PR DESCRIPTION
**Pull request by anhu**

### CODE REVIEW

**Review by baentsch — CHANGES_REQUESTED** [review]
Thanks very much for your contribution. Some questions/suggestions for improvement:
- There should be some explanatory text in the PR commit (goal, audience, etc.; maybe pointing to READMEs).
- The README provided is _very_ brief. We typically don't assume too much background knowledge of OQS-demos users, i.e., everything should be obvious to build and run. Please have a look at the README.md (basic overview and build instructions) and USAGE.md files (how to deploy the docker image) in the other demos. The latter is meant to be put up at hub.docker.com "for the unwary": See e.g., https://hub.docker.com/repository/docker/openquantumsafe/curl. So please add those.
- Lastly, and correct me if I'm wrong as I have to infer things from looking only at code here, this seems like a pure (PQ?)[wolfssl](https://www.wolfssl.com/) extension without any relation whatsoever to OQS: Please correct me if I'm wrong. If I'm not wrong, would it be appropriate to request adding also all code points for the [oqs-openssl](https://github.com/open-quantum-safe/openssl) such as to wireshark-enable that implementation too? Going beyond that -- what about aiming at achieving interoperability between (PQ-)`wolfssl` and `oqs-openssl`?

**Comment by baentsch** [comment]
@anhu When trying to write user documentation for this image myself, I first wanted to use this and miserably failed: Build went OK,  `docker run -ti --net=host --privileged -v $HOME:/root:ro -e XAUTHORITY=/root/.Xauthority -e DISPLAY=$DISPLAY oqs-wireshark wireshark`  (sharing network interface and X-Windows DISPLAY) gets the window up, but then the console shows the following error messages (the last one appears for every mouse move and no text box is rendered OK):
```
$ docker run -it --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" oqs-wireshark wireshark
12:52:22.351     Main Warn QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open i915 (search paths /usr/lib/xorg/modules/dri)
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/xorg/modules/dri)
libGL error: failed to load driver: swrast
12:52:26.450     Main Warn QFont::setPointSizeF: Point size <= 0 (-0.750000), must be greater than 0
```

-> Do you have suggestions how to resolve this/how to get wireshark to render OK? Any prerequisites on the host that I may not have? 

Additional information: When creating a "plain ubuntu wireshark docker image" (installed into the docker image via `apt`), and running via the `docker run` command above, `wireshark` renders just fine....

**Comment by anhu** [comment]
I must admit that this PR has been somewhat of a lower priority and therefore I have been a bit sloppy. I didn't actually make it to execution of wireshark. I apologize for putting up a PR without fully trying the results.  I should have some time within the next few days to look into this.

**Comment by baentsch** [comment]
That'd be great: Thanks & looking forward to that!

The use case I'm thinking about (supporting/documenting) goes about like this: 
- Start wireshark (docker image)
- Enable filter for 149.81.106.123 (test.openquantumsafe.org interop server)
- Execute (via other docker image) (oqs-)`curl -k https://test.openquantumsafe.org:6001 --curves frodo640aes`
- Show/analyze TLS traffic in wireshark

--> Would you consider this realistic? My first mini-steps are pretty disappointing: It seems the Ubuntu-stock `wireshark` doesn't even recognize this as TLS traffic, let alone permitting analysis thereof :-( But then again, my wireshark "know-how" is dismal.

**Comment by anhu** [comment]
> Would you consider this realistic?  

Yes!! Very realistic! In fact, it very much mirrors our own demo. 

1. start apache httpd built against wolfssl and liboqs
2. start wireshark (locally built, not docker image) and watch loopback
3. execute curl using falcon root cert and specify quantum safe group beside `--curves`. 
4. show analyze tls traffic in wireshark. 

If you stay tuned to wolfSSL's YouTube channel or get notifications of wolfSSL's webinars, sometime in the month of December, you'll probably be able to see such a demo. 

From what I remember stock, wireshark should recognize the traffic as TLS but not understand any of the groups nor signature schemes.  So, maybe something else has gone wrong? 

Another minor point is that you specify `frodo640aes` but please note that the patch does not allow for recognition of that particular codepoint.  Only SABER, KYBER, NTRU and their hybrids codepoints are recognized.  Of course, if you would like to add it, please feel free to do so.

**Comment by anhu** [comment]
@baentsch , 

I noticed that all the other demos that are "docker-ified" are command-line utilities or servers; none of them have GUIs. The only demo that does have a GUI is chromium but it is not "docker-ified" . Perhaps it would be more appropriate if this was done more like chromium and just built without docker? I must admit that my docker know-how is dismal. 

Please let me know your opinion on this matter.

**Comment by baentsch** [comment]
> Yes!! Very realistic!

Thanks for that confirmation. Could you then please help fill my "wireshark knowledge holes" as per the below?

> From what I remember stock, wireshark should recognize the traffic as TLS but not understand any of the groups nor signature schemes. So, maybe something else has gone wrong?

It looks like this: A plain vanilla wireshark running with the filter "ip.addr == 149.81.106.123" does not recognize TLS traffic when observing curl (successfully) connecting to our OQS-test server: `docker run -it openquantumsafe/curl sh -c "curl -k https://test.openquantumsafe.org:6007 --curves kyber512"` but shows this:
grafik

Looks like it considers this X11 traffic... What am I doing wrong?

> Another minor point is that you specify frodo640aes but please note that the patch does not allow for recognition of that particular codepoint. Only SABER, KYBER, NTRU and their hybrids codepoints are recognized. Of course, if you would like to add it, please feel free to do so.

Agreed, so see above: This is contacting a "Kyber-enabled" port (6007) which I think the patched wireshark should work with, right?

> Perhaps it would be more appropriate if this was done more like chromium and just built without docker? [...] Please let me know your opinion on this matter.

Agreed again: I'm all for taking small steps: 
1) Probably should be a shell script building a working `wireshark` on an Ubuntu x64
2) Adding the patch then
3) Running this against the test server with an algorithm readily supported by the patch demoing the scenario described above
4) Adding all other OQS algorithms thus creating a wireshark working for both wolfssl and oqs-openssl
5) Moving (and testing) the build to Alpine (but maybe only later -- this is just to save size)
6) Moving it into a docker image

--> What'd you say, @anhu: Reasonable? Any steps you could contribute (without going against your business commitments)? With a bit of help around understanding wireshark I think I may also take them on if that'd ease things.

**Comment by baentsch** [comment]
@anhu: Please check out [this script](https://github.com/open-quantum-safe/oqs-demos/blob/mb-wireshark/wireshark/build.sh) as a first cut implementing items 1-4 above (supporting all OQS, incl. hybrid, algorithm IDs). The resultant `wireshark` executable runs locally with the same issues as described above for a "standard-issue"/apt-installed `wireshark`: It doesn't properly recognize/dissect TLS traffic directed towards the OQS-TLS interop server (but still thinks this is X11 traffic). Suggestions regarding that problem (but also for improvement) _very_ welcome.

**Comment by baentsch** [comment]
OK, works like a charm now, even for hybrid algorithms: 
grafik

I'll now try to "dockerize" this so you can try the image with a wolfssl install, @anhu.

As for the demo I'm not sure whether we should make this self-contained (also containing QSC-TLS server, say apache, and client, say curl, alongside wireshark or just `wireshark`... Opinions? @dstebila ?

**Comment by anhu** [comment]
Wow....lots of progress!!  Sorry I haven't  been able to reply to your messages.  I'm in the North American Eastern time zone. :)

**Comment by baentsch** [comment]
>  I'm in the North American Eastern time zone.

Ah, OK -- sorry, for whichever reason I thought you're based in France.

**Comment by dstebila** [comment]
Nice progress Michael!

> As for the demo I'm not sure whether we should make this self-contained (also containing QSC-TLS server, say apache, and client, say curl, alongside wireshark or just `wireshark`... Opinions? @dstebila ?

Is it easy for a Docker-ized wireshark to be able to capture transmissions between things outside of its container?  If someone has to successfully orchestrate three containers (wireshark, Apache, curl) to be able to run this, that's pretty rough.  In which case I'd be inclined to throw Apache and curl in there, so that they have something that they can more easily start using.

**Comment by anhu** [comment]
> Ah, OK -- sorry, for whichever reason I thought you're based in France.

Hahaha.... I wish I was in France right now.  I'm actually in the same city as @dstebila ; Waterloo, Ontario, Canada. And I agree with him, great progress!

**Comment by baentsch** [comment]
@anhu Please check out the "alternative PR" #105: It works OK and supports all OQS algorithms. I chose a different way to patch the wireshark code such as to allow you to re-use this for WolfSSL: All that's needed is a suitable header file defining the names; see [qsc.h](https://github.com/open-quantum-safe/openssl/blob/mb-wiresharkregistry/qsc.h) as to how I'm proposing it for the OQS case. If you're OK with that, I'd suggest we close this PR and move #105 forward. Thanks again for the initiative and initial work!

@dstebila Please check out https://github.com/open-quantum-safe/openssl/pull/340 as to whether you're OK with the proposed way to provide the required OpenSSL information to Wireshark (and possibly other users of this general "name/ID mapping").

**Comment by anhu** [comment]
Hi @baentsch , 
My original intention when reaching out to the OQS team was to show how easy it was to get wireshark to display the OIDs and codepoints and to encourage the OQS team to do an integration.  I think its safe to say I was successful so I will happily close this PR.  

Would you be willing to host another patch that builds on top of your wireshark work that switches to wolfSSL's naming convention?

**Comment by baentsch** [comment]
> Would you be willing to host another patch that builds on top of your wireshark work that switches to wolfSSL's naming convention?

I'm not sure I understand how both should be made switchable, but sure, please suggest a PR so I get it. If you mean instructions to build an entirely different executable (?) then of course it's clear and I can already amend #105 easily.

**Comment by anhu** [comment]
Please disregard.  Your adjustments to PR 105 are are even better than what I wanted.

**Pull request closed without merging**
