### PR TITLE
upstream algorithm naming update

### PR DESCRIPTION
**Pull request by baentsch**
Update pursuant https://github.com/open-quantum-safe/liboqs/pull/1467

### CODE REVIEW

**Review by baentsch — COMMENTED** [review]
@xvzcf I intentionally refrained from making the changes you've introduced in this commit as we have no control over what wolfssl does in their code (keeping or removing these algorithms). @anhu: Can you comment?

**Comment by anhu** [comment]
It appears the changes here remove Dilithium AES and Kyber 90S variants.  That is in line with what we have done in the wolfSSL library as well so I am in full support. 

@baentsch , I'm good with this change.

Warm regards, Anthony

**Comment by xvzcf** [comment]
Is there a reason the wireshark changes were undone?

**Comment by baentsch** [comment]
> Is there a reason the wireshark changes were undone?

No. Don't understand that. Would you want to add it again and then merge (I'm away from my Computer right now)?

**Pull request merged**
