### PR TITLE
Update test server build script: liboqs-0.10.1 & oqs-provider-0.6.1-rc1

### LINKED ISSUE #271: Update test server with liboqs 0.10.0 release

### PR DESCRIPTION
**Pull request by bhess**
Update test server build script to use liboqs 0.10.0 & oqs-provider-0.6.0-rc1.

Resulting build is deployed at test.openquantumsafe.org and all tests with `testrun.sh` pass.

Closes #271

### CODE REVIEW

**Comment by bhess** [comment]
The update is pointing to the final release and is deployed. All tests pass.

**Comment by dstebila** [comment]
Should this be merged?

**Comment by bhess** [comment]
Yes, ready to merge.

**Review by baentsch — APPROVED** [review]
Conceptually OK but didn't capture all references to `liboqs` and `oqsprovider`; also CI failed. Please rebase to "main" after #275 landed fixing those issues.

**Comment by bhess** [comment]
Updated PR with an update to liboqs-0.10.1 & oqs-provider 0.6.1-rc1. Deployed at test.openquantumsafe.org, the test-run passes.

**Comment by baentsch** [comment]
Re-based in the absence of @bhess to get clean CI.

**Comment by baentsch** [comment]
@bhess -- reminder regarding our merge convention: The author merges after enough approvals are available. I'm doing the merge now as I learned you're absent such as to get to a clean (CI) state before the project revamp your colleagues want to lead.

**Comment by bhess** [comment]
Thanks @baentsch !

**Pull request merged**
