### PR TITLE
Dockerfile Upgrades and Optimizations

### PR DESCRIPTION
**Pull request by BusyKhalid**
This pull request introduces multiple updates to improve build efficiency, reduce image size, and increase the stability of the Dockerfiles. Key changes include:

- **Base Image Upgrades**:
  - Upgraded to `Ubuntu 24.04` and `Alpine 3.20.3`.
  - Updated Wireshark to version `4.4.1`.

- **Optimizations in Dockerfile Build Stages**:
  - Replaced `apt` with `apt-get` and added `--no-install-recommends` to minimize unnecessary packages in Ubuntu-based images.
  - Simplified `apk` commands with `--no-cache` and removed `apk upgrade` in Alpine-based images to reduce image size and improve stability.
  - Standardized download commands to use `curl` over `wget` for consistency.
  
- **Efficiency Improvements**:
  - Streamlined directory handling using `WORKDIR` instead of multiple `RUN mkdir` commands.
  - Cleaned up `apt` and `apk` cache to reduce final image sizes.

### CODE REVIEW

**Review by SWilson4 — COMMENTED** [review]
These changes look good to me—thanks very much for the contribution—but I imagine that you and @ajbozarth will want to coordinate to ensure a smooth merge.

**Comment by ajbozarth** [comment]
On an initial read through the `curl` `openssl3` and `openvpn` updates should merge with #298 with just a handful of minor conflicts caused by my addition of `ENV` vars for pinning versions. As for the wireshark update, I'll try it out later, but if I'm reading it correctly all the changes are generally cosmetic, and would not invalidate deprecating in in #298 

@BusyKhalid just curious how did you test these updates and in what environments?

**Comment by BusyKhalid** [comment]
I will close the pull request until I compl

**Comment by BusyKhalid** [comment]
> These changes look good to me—thanks very much for the contribution—but I imagine that you and @ajbozarth will want to coordinate to ensure a smooth merge.

Thanks for the feedback! I’ve closed this PR for now as I plan to make further changes and address a few mistakes I overlooked.

**Comment by BusyKhalid** [comment]
> On an initial read through the `curl` `openssl3` and `openvpn` updates should merge with #298 with just a handful of minor conflicts caused by my addition of `ENV` vars for pinning versions. As for the wireshark update, I'll try it out later, but if I'm reading it correctly all the changes are generally cosmetic, and would not invalidate deprecating in in #298
> 
> @BusyKhalid just curious how did you test these updates and in what environments?

Appreciate the insights! I tested locally on Windows 11. Closing for now to make some refinements before resubmitting.

**Comment by BusyKhalid** [comment]
> On an initial read through the `curl` `openssl3` and `openvpn` updates should merge with #298 with just a handful of minor conflicts caused by my addition of `ENV` vars for pinning versions. As for the wireshark update, I'll try it out later, but if I'm reading it correctly all the changes are generally cosmetic, and would not invalidate deprecating in in #298
> 
> @BusyKhalid just curious how did you test these updates and in what environments?

I appreciate the insights. I tested locally on Windows 11. Closing for now to make some refinements before resubmitting.

**Comment by SWilson4** [comment]
Please feel free to mark as draft rather than closing if you intend to reopen it later.

**Pull request closed without merging**
